/**
 * Generates `src/plugins/icons.data.ts` — an offline, tree-shaken subset of the
 * Iconify collections containing only the icons this app actually references.
 *
 * Bundling the full sets is not an option: lucide is ~85 KB gzip and mdi ~720 KB.
 * This scans the source for `prefix:name` icon references and extracts just those.
 *
 * Run after adding a new icon:  npm run icons
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getIcons } from '@iconify/utils'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const PREFIXES = ['lucide', 'mdi']
const ICON_RE = new RegExp(`\\b(${PREFIXES.join('|')}):([a-z0-9]+(?:-[a-z0-9]+)*)\\b`, 'g')

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) return entry === 'node_modules' ? [] : walk(path)
    return /\.(vue|ts|js)$/.test(path) ? [path] : []
  })
}

const used = Object.fromEntries(PREFIXES.map((p) => [p, new Set()]))
for (const file of walk(join(root, 'src'))) {
  const source = readFileSync(file, 'utf8')
  for (const [, prefix, name] of source.matchAll(ICON_RE)) used[prefix].add(name)
}

const collections = []
for (const prefix of PREFIXES) {
  const names = [...used[prefix]].sort()
  if (!names.length) {
    // Still emit the collection so the generated module stays importable.
    collections.push({ prefix, names, subset: { prefix, icons: {} } })
    continue
  }

  const full = JSON.parse(readFileSync(join(root, 'node_modules/@iconify-json', prefix, 'icons.json'), 'utf8'))
  const subset = getIcons(full, names)
  if (!subset) throw new Error(`Could not build subset for "${prefix}"`)

  const missing = names.filter((name) => !(name in subset.icons) && !(name in (subset.aliases ?? {})))
  if (missing.length) throw new Error(`Unknown ${prefix} icons: ${missing.join(', ')}`)

  collections.push({ prefix, names, subset })
}

const body = collections
  .map(({ prefix, names, subset }) =>
    `/** ${names.length} icons from the "${prefix}" set. */\n` +
    `export const ${prefix}: IconifyJSON = ${JSON.stringify(subset)}`
  )
  .join('\n\n')

writeFileSync(
  join(root, 'src/plugins/icons.data.ts'),
  '// GENERATED BY scripts/build-icons.mjs — DO NOT EDIT. Run `npm run icons` to refresh.\n' +
    "import type { IconifyJSON } from '@iconify/vue'\n\n" +
    body +
    '\n',
)

console.log(collections.map(({ prefix, names }) => `${prefix}: ${names.length} icons`).join('\n'))
