-- Online Pathshala — seed data (idempotent).
-- INSERT IGNORE means re-running skips rows that already exist, so this is safe
-- to run every deploy. Demo accounts below all use the password:  Test@1234

-- Upsert the demo accounts so the known password (Test@1234) is always in effect,
-- even if these emails already exist from an older seed.
INSERT INTO users (full_name, email, password, user_role) VALUES
  ('Test Admin',   'admin@test.com',   '$2b$10$tvyWXLNdUaSj68emJVYUF.4Eh65vsQbevgt/YtMNQJntnOqo5T/Gq', 'Admin'),
  ('Test Student', 'student@test.com', '$2b$10$2m7LHysaBoHokx4Fb0P16.DFJpaWJ3neJJOUQ7Wy8bfVriEKNGtjC', 'Student'),
  ('Test Tutor',   'tutor@test.com',   '$2b$10$pQb.FxTr2AGoZhzkQS9Q3eqPMrdsmRwFgHmbafR/1A/wgTsf34TxC', 'Tutor')
ON DUPLICATE KEY UPDATE
  password  = VALUES(password),
  full_name = VALUES(full_name),
  user_role = VALUES(user_role);

INSERT IGNORE INTO courses (id, author, category, price, rating, subtitle, thumb_url, title) VALUES
  (10010, 'Vimlesh Kumar', 'Development', 1117.99, 4.50, 'Learn Python like a Professional. Start from the basics and go all the way to creating your own applications and games.', 'https://i3.ytimg.com/vi/XKHEtdqhLK8/maxresdefault.jpg', 'Complete Python Bootcamp'),
  (10011, 'Dani Krossing', 'Development', 2118.99, 4.50, 'Master fundamentals with JavaScript exercises, projects, live examples & more', 'https://i3.ytimg.com/vi/jS4aFq5-91M/maxresdefault.jpg', 'Learn JavaScript Programming'),
  (10012, 'Caleb Curry', 'Development', 4119.99, 3.50, 'Obtain valuable Core Java Skills And Java Certification', 'https://i3.ytimg.com/vi/GoXwIVyNvX0/maxresdefault.jpg', 'Java Programming Essentials'),
  (10013, 'Gareth David Studio', 'PhotoVideo', 4111.99, 4.50, 'Learn graphic design, logo design, and more with this in-depth, practical, easy-to-follow course!', 'https://i3.ytimg.com/vi/9EGI-FSr0Ig/maxresdefault.jpg', 'Beginners Guide To Adobe Illustrator'),
  (10014, 'chinfat', 'PhotoVideo', 2112.50, 3.50, 'Learn Beginner-Advanced Video Editing, Audio Editing, Color Grading, Motion Graphics, and more', 'https://i3.ytimg.com/vi/u99i1SmDgIc/maxresdefault.jpg', 'Learn Adobe Premiere Pro CC'),
  (10015, 'Jacob Clifford', 'Finance', 1115.99, 4.50, 'The Easiest Beginner level Course on Economics with real life examples and graphic content. Perfect for Newbies!', 'https://i3.ytimg.com/vi/g9aDizJpd_s/maxresdefault.jpg', 'Crash Course Economics'),
  (10016, 'MrandMrsMuscle', 'Health', 1448.99, 3.50, 'This course will help jump-start your body to lose belly fat, lose weight and guide you with a 14 day exercise plan. NO EQUIPMENT needed', 'https://i3.ytimg.com/vi/By6GXzcldGY/maxresdefault.jpg', 'Lose Belly Fat in 14 Days'),
  (10017, 'Robert Kiyosaki', 'Real Estate', 2441.99, 4.50, 'Learn professional investment techniques for real estate investing in residential and commercial properties', 'https://i3.ytimg.com/vi/UJv9-F7SN5A/maxresdefault.jpg', 'Real Estate Investing'),
  (10018, 'Bill Hilton', 'Music', 1445.99, 4.50, 'Learn Piano in WEEKS not years. Play-By-Ear & learn to Read Music. Pop, Blues, Jazz, Ballads, Classical', 'https://i3.ytimg.com/vi/WJ3-F02-F_Y/maxresdefault.jpg', 'How To Play Piano for Beginners'),
  (10019, 'TTFS', 'Office', 4766.99, 3.50, 'Microsoft Excel Beginner to Professional. Includes Pivot Tables, Power Query, NEW Formulas', 'https://i3.ytimg.com/vi/Vl0H-qTclOg/maxresdefault.jpg', 'Master Microsoft Excel');

INSERT IGNORE INTO course_objectives (id, objective, course_id) VALUES
  (1, 'Be able to program in Python professionally', 10010),
  (2, 'Build GUIs and Desktop applications with Python', 10010),
  (3, 'Be able to build fully fledged websites and web apps with Python', 10010),
  (4, 'Create a portfolio of Python projects to apply for developer jobs', 10010),
  (5, 'Be able to build fully fledged websites and web apps with Python', 10010),
  (6, 'All about variables, functions, objects and arrays', 10011),
  (7, 'Modern ES6 from the beginning: arrow functions, destructuring, spread operator, optional chaining', 10011),
  (8, 'Project-driven learning with plenty of examples', 10011),
  (9, 'Asynchronous JavaScript: Event loop, promises, async/await, AJAX calls and APIs', 10011),
  (10, 'Complex concepts like the ''this'' keyword, higher-order functions, closures', 10011),
  (11, 'Learn industry best practices in Java software development from a professional', 10012),
  (12, 'Obtain proficiency in Java 8 and Java 11', 10012),
  (13, 'Be able to demonstrate your understanding of Java to future employers', 10012),
  (14, 'Acquire essential java basics for transitioning to the Spring Framework, Java EE, Android', 10012),
  (15, 'Master Exceptions, IO, Collections Framework, Generics, Multi-threading, Databases', 10012),
  (16, 'Master advanced Illustrator tools and techniques', 10013),
  (17, 'Design your own graphics, without any experience', 10013),
  (18, 'Create custom typography', 10013),
  (19, 'Take hand drawings and recreate them using Illustrator', 10013),
  (20, 'Export your projects for print, web, or other design projects', 10013),
  (21, 'Edit an entire video from beginning to end, using professional and efficient techniques', 10014),
  (22, 'Master Premiere Pro and be CONFIDENT Editing Your Own Videos', 10014),
  (23, 'Learn how to edit social media clips for Instagram, Facebook, Twitter & YouTube Stories', 10014),
  (24, 'How to organize your video editing footage like a Pro', 10014),
  (25, 'Add a feeling to your video with color grading', 10014),
  (26, 'Acquire a solid understanding of key economic relationships', 10015),
  (27, 'Understand business cycles', 10015),
  (28, 'Using demand and supply, illustrate price determination', 10015),
  (29, 'Examine the impact of tax/subsidies', 10015),
  (30, 'Decluttering and impact on economy', 10015),
  (31, 'Understand the fundamentals of weight loss', 10016),
  (32, 'Develop healthy eating habits', 10016),
  (33, 'Stay motivated for long term results', 10016),
  (34, 'Lose weight Naturally within 2 weeks', 10016),
  (35, 'Have a healthy relationship with food', 10016),
  (36, 'Confidently analyze multifamily real estate investment opportunities', 10017),
  (37, 'Use Professional Grade Investment Models to Evaluate Your Deals', 10017),
  (38, 'Use Smart Investment Deal Structures With Business Partners', 10017),
  (39, 'Evaluate Rental Income Properties', 10017),
  (40, 'Know a ''Good'' Investment from a ''Bad'' Investment', 10017),
  (41, 'You will learn to read sheet music AS you learn to play-by-ear', 10018),
  (42, 'You get to sound like a pro right from the start', 10018),
  (43, 'Learn to play the piano without theory', 10018),
  (44, 'Master unique tips & techniques that you wont find in ANY other course, guaranteed', 10019),
  (45, 'Build a solid understanding on the Basics of Microsoft Excel', 10019),
  (46, 'Maintain large sets of Excel data in a list or table', 10019),
  (47, 'Write advanced conditional, text, date and lookup functions, including XLOOKUP', 10019),
  (48, 'Get LIFETIME access to project files, quizzes, homework exercises', 10019),
  (49, 'Navigating the keyboard', 10018),
  (50, 'Basic improvisation', 10018);

-- Course lessons / curriculum. video_key is the YouTube video id (free player).
-- Idempotent via explicit ids + INSERT IGNORE.
INSERT IGNORE INTO lesson (id, duration, course_id, lesson_name, video_key, section_name) VALUES
  (1,  '08:24', 10010, 'Introduction & Overview',       'XKHEtdqhLK8', 'Getting Started'),
  (2,  '15:10', 10010, 'Core Concepts',                 'XKHEtdqhLK8', 'Core Content'),
  (3,  '12:47', 10010, 'Project & Next Steps',          'XKHEtdqhLK8', 'Core Content'),
  (4,  '07:58', 10011, 'Introduction & Overview',       'jS4aFq5-91M', 'Getting Started'),
  (5,  '18:32', 10011, 'Core Concepts',                 'jS4aFq5-91M', 'Core Content'),
  (6,  '10:05', 10011, 'Project & Next Steps',          'jS4aFq5-91M', 'Core Content'),
  (7,  '09:12', 10012, 'Introduction & Overview',       'GoXwIVyNvX0', 'Getting Started'),
  (8,  '16:44', 10012, 'Core Concepts',                 'GoXwIVyNvX0', 'Core Content'),
  (9,  '13:20', 10012, 'Project & Next Steps',          'GoXwIVyNvX0', 'Core Content'),
  (10, '06:40', 10013, 'Introduction & Overview',       '9EGI-FSr0Ig', 'Getting Started'),
  (11, '14:18', 10013, 'Core Concepts',                 '9EGI-FSr0Ig', 'Core Content'),
  (12, '11:03', 10013, 'Project & Next Steps',          '9EGI-FSr0Ig', 'Core Content'),
  (13, '08:50', 10014, 'Introduction & Overview',       'u99i1SmDgIc', 'Getting Started'),
  (14, '17:27', 10014, 'Core Concepts',                 'u99i1SmDgIc', 'Core Content'),
  (15, '12:09', 10014, 'Project & Next Steps',          'u99i1SmDgIc', 'Core Content'),
  (16, '07:33', 10015, 'Introduction & Overview',       'g9aDizJpd_s', 'Getting Started'),
  (17, '15:55', 10015, 'Core Concepts',                 'g9aDizJpd_s', 'Core Content'),
  (18, '10:41', 10015, 'Project & Next Steps',          'g9aDizJpd_s', 'Core Content'),
  (19, '09:06', 10016, 'Introduction & Overview',       'By6GXzcldGY', 'Getting Started'),
  (20, '13:48', 10016, 'Core Concepts',                 'By6GXzcldGY', 'Core Content'),
  (21, '11:52', 10016, 'Project & Next Steps',          'By6GXzcldGY', 'Core Content'),
  (22, '08:15', 10017, 'Introduction & Overview',       'UJv9-F7SN5A', 'Getting Started'),
  (23, '16:02', 10017, 'Core Concepts',                 'UJv9-F7SN5A', 'Core Content'),
  (24, '12:33', 10017, 'Project & Next Steps',          'UJv9-F7SN5A', 'Core Content'),
  (25, '07:21', 10018, 'Introduction & Overview',       'WJ3-F02-F_Y', 'Getting Started'),
  (26, '14:39', 10018, 'Core Concepts',                 'WJ3-F02-F_Y', 'Core Content'),
  (27, '10:58', 10018, 'Project & Next Steps',          'WJ3-F02-F_Y', 'Core Content'),
  (28, '08:44', 10019, 'Introduction & Overview',       'Vl0H-qTclOg', 'Getting Started'),
  (29, '17:11', 10019, 'Core Concepts',                 'Vl0H-qTclOg', 'Core Content'),
  (30, '13:05', 10019, 'Project & Next Steps',          'Vl0H-qTclOg', 'Core Content');
